[database1]
host = "mysql"
port = 3306
db-name = "gochatapp" #データベース2つのときはresistration
charset = "utf8"
user = "enomoto"

#dockerでは使用しない
#[database2]
#host = "mysql"
#port = 3306
#db-name = "chatrooms"
#charset = "utf8"
#user = "enomoto"